doc-warnings: true
test-warnings: false
strictness: medium
max-line-length: 99
uses:
  - django
autodetect: true
requirements:
  - requirements.txt
ignore-paths:
  - contrib
  - ops
python-targets:
  - 3
