version: '2'

services:
  app:
    restart: always
    build: .
    links:
      - postgres:postgres
    env_file: .env
    command: python -m twitter_connector

  postgres:
    build: ./ops/dev/postgres
    volumes_from:
      - data
    ports:
      - "5435:5435"

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"