# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_connector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hashtag',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hashtagurl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tweet',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tweeturl',
            table=None,
        ),
        migrations.AlterModelTable(
            name='url',
            table=None,
        ),
    ]
