# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_connector', '0002_auto_20161201_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='url',
            name='modified_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='modified_at'),
        ),
    ]
