# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_connector', '0003_auto_20161201_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expanded_url',
            field=models.TextField(unique=True, verbose_name='expanded_url'),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.TextField(verbose_name='url'),
        ),
    ]
